test_debug_build:
  image: greenaddress/webfiles@sha256:2a5cbacce2f754598b40874526acdf3ac506c765fd1aa558a88e1842351888f3
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./prepare.sh
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt --require-hashes
    - python render_templates.py -a ..
