language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/walletcrx greenaddress/walletcrx@sha256:21451ff70e639a2a5c8fb8434b9593626c323a8ffd9372db5ee8bafc512de74f /bin/bash -c "cd /walletcrx && ./prepare.sh && virtualenv venv && source venv/bin/activate && pip install -r requirements.txt --require-hashes && python render_templates.py -a .."
